import { describe, expect, it } from "vitest";
import { renderWebConsoleHtml } from "../../apps/gateway-orchestrator/src/ui/render_web_console";

describe("renderWebConsoleHtml", () => {
  it("renders core sections and endpoint usage hints", () => {
    const html = renderWebConsoleHtml();

    expect(html).toContain("Alfred Test Console");
    expect(html).toContain("/v1/messages/inbound");
    expect(html).toContain("/v1/whatsapp/baileys/inbound");
    expect(html).toContain("/v1/memory/search");
    expect(html).toContain("/v1/auth/openai/start");
    expect(html).toContain("/v1/auth/openai/status");
    expect(html).toContain("/v1/auth/openai/rate-limits");
    expect(html).toContain("/v1/auth/openai/disconnect");
    expect(html).toContain("/v1/whatsapp/live/status");
    expect(html).toContain("/v1/whatsapp/live/connect");
    expect(html).toContain("/v1/whatsapp/live/disconnect");
    expect(html).toContain("/v1/identity/mappings");
    expect(html).toContain("/v1/identity/resolve");
    expect(html).toContain("/v1/stream/events/subscribe");
    expect(html).toContain("Job Controls");
    expect(html).toContain("id=\"authPreference\"");
    expect(html).toContain("LLM Auth Mode");
    expect(html).toContain("OAuth (OpenAI)");
    expect(html).toContain("Live WhatsApp (Baileys)");
    expect(html).toContain("WhatsApp Setup Flow");
    expect(html).toContain("id=\"waLiveBadge\"");
    expect(html).toContain("id=\"waSetupNext\"");
    expect(html).toContain("id=\"waCopyEnv\"");
    expect(html).toContain("id=\"waQrImage\"");
    expect(html).toContain("id=\"waQrHint\"");
    expect(html).toContain("renderWaQrPreview");
    expect(html).toContain("qrImageDataUrl");
    expect(html).toContain("WA_LIVE_AUTO_POLL_MS");
    expect(html).toContain("SOURCE_AUTO_POLL_MS");
    expect(html).toContain("STREAM_AUTO_POLL_MS");
    expect(html).toContain("startWaLiveAutoPoll");
    expect(html).toContain("startSourceAutoPoll");
    expect(html).toContain("startInteractionStreamPoll");
    expect(html).toContain("id=\"sourceGatewayCard\"");
    expect(html).toContain("id=\"sourceAuthCard\"");
    expect(html).toContain("id=\"sourceWaCard\"");
    expect(html).toContain("id=\"sourceMemoryCard\"");
    expect(html).toContain("id=\"sourceRefresh\"");
    expect(html).toContain("id=\"streamRefresh\"");
    expect(html).toContain("id=\"logInteractionStream\"");
    expect(html).toContain("id=\"includeNoisyStream\"");
    expect(html).toContain("id=\"mapBind\"");
    expect(html).toContain("id=\"mapResolve\"");
    expect(html).toContain("id=\"mapList\"");
    expect(html).toContain("Log source changes");
    expect(html).toContain("updateSourceSnapshot");
    expect(html).toContain("/v1/stream/events");
    expect(html).toContain("streamEventsUrl");
    expect(html).toContain("WHATSAPP_PROVIDER=baileys");
    expect(html).toContain("SEND_CHAT_REQUEST");
    expect(html).toContain("selectedAuthPreference");
    expect(html).toContain("Persisted Transcript");
    expect(html).toContain("id=\"sessionTranscript\"");
    expect(html).toContain("id=\"transcriptRefresh\"");
    expect(html).toContain("pollTranscriptSilently");
    expect(html).toContain("startTranscriptAutoPoll");
    expect(html).toContain(".status[data-state=\"busy\"]");
    expect(html).toContain("id=\"logNewestFirst\"");
    expect(html).toContain("Newest first");
    expect(html).toContain("id=\"authSummary\"");
    expect(html).toContain("id=\"waLiveSummary\"");
    expect(html).toContain("runButtonAction");
  });
});
