import { describe, expect, it } from "vitest";
import { renderWebConsoleHtml } from "../../apps/gateway-orchestrator/src/ui/render_web_console";

describe("renderWebConsoleHtml", () => {
  it("renders core sections and endpoint usage hints", () => {
    const html = renderWebConsoleHtml();

    expect(html).toContain("Alfred Test Console");
    expect(html).toContain("href=\"/ui\"");
    expect(html).toContain("href=\"/ui/transcripts\"");
    expect(html).toContain("href=\"/ui/console\"");
    expect(html).toContain("/v1/messages/inbound");
    expect(html).toContain("/v1/whatsapp/baileys/inbound");
    expect(html).toContain("/v1/memory/search");
    expect(html).toContain("/v1/memory/checkpoints/status");
    expect(html).toContain("/v1/heartbeat/status");
    expect(html).toContain("/v1/heartbeat/configure");
    expect(html).toContain("/v1/heartbeat/run");
    expect(html).toContain("/v1/auth/openai/start");
    expect(html).toContain("/v1/auth/openai/status");
    expect(html).toContain("/v1/auth/openai/rate-limits");
    expect(html).toContain("/v1/auth/openai/disconnect");
    expect(html).toContain("/v1/whatsapp/live/status");
    expect(html).toContain("/v1/whatsapp/live/connect");
    expect(html).toContain("/v1/whatsapp/live/disconnect");
    expect(html).toContain("/v1/identity/mappings");
    expect(html).toContain("/v1/identity/resolve");
    expect(html).toContain("/v1/stream/events/subscribe");
    expect(html).toContain("Job Controls");
    expect(html).toContain("Run Timeline");
    expect(html).toContain("id=\"runSessionKey\"");
    expect(html).toContain("id=\"runId\"");
    expect(html).toContain("id=\"runList\"");
    expect(html).toContain("id=\"runStatus\"");
    expect(html).toContain("RUNS_LIST");
    expect(html).toContain("RUN_STATUS");
    expect(html).toContain("id=\"authPreference\"");
    expect(html).toContain("LLM Auth Mode");
    expect(html).toContain("OAuth (OpenAI)");
    expect(html).toContain("Heartbeat");
    expect(html).toContain("id=\"heartbeatStatus\"");
    expect(html).toContain("id=\"heartbeatRun\"");
    expect(html).toContain("id=\"heartbeatSave\"");
    expect(html).toContain("id=\"heartbeatSummary\"");
    expect(html).toContain("id=\"heartbeatAlertOnAuthDisconnected\"");
    expect(html).toContain("id=\"heartbeatAlertOnWhatsAppDisconnected\"");
    expect(html).toContain("id=\"heartbeatAlertOnStuckJobs\"");
    expect(html).toContain("id=\"heartbeatStuckJobThresholdMinutes\"");
    expect(html).toContain("id=\"memoryCheckpointStatus\"");
    expect(html).toContain("id=\"sourceHeartbeatCard\"");
    expect(html).toContain("id=\"sourceHeartbeatValue\"");
    expect(html).toContain("id=\"sourceHeartbeatMeta\"");
    expect(html).toContain("Live WhatsApp (Baileys)");
    expect(html).toContain("WhatsApp Setup Flow");
    expect(html).toContain("id=\"waLiveBadge\"");
    expect(html).toContain("id=\"waSetupNext\"");
    expect(html).toContain("id=\"waCopyEnv\"");
    expect(html).toContain("id=\"waQrImage\"");
    expect(html).toContain("id=\"waQrHint\"");
    expect(html).toContain("renderWaQrPreview");
    expect(html).toContain("qrImageDataUrl");
    expect(html).toContain("WA_LIVE_AUTO_POLL_MS");
    expect(html).toContain("SOURCE_AUTO_POLL_MS");
    expect(html).toContain("STREAM_AUTO_POLL_MS");
    expect(html).toContain("STREAM_PLANNER_TRACE");
    expect(html).toContain("plannerChosenAction");
    expect(html).toContain("plannerTrace");
    expect(html).toContain("startWaLiveAutoPoll");
    expect(html).toContain("startSourceAutoPoll");
    expect(html).toContain("startInteractionStreamPoll");
    expect(html).toContain("id=\"sourceGatewayCard\"");
    expect(html).toContain("id=\"sourceAuthCard\"");
    expect(html).toContain("id=\"sourceWaCard\"");
    expect(html).toContain("id=\"sourceMemoryCard\"");
    expect(html).toContain("id=\"sourceRefresh\"");
    expect(html).toContain("id=\"streamRefresh\"");
    expect(html).toContain("id=\"logInteractionStream\"");
    expect(html).toContain("id=\"includeNoisyStream\"");
    expect(html).toContain("id=\"mapBind\"");
    expect(html).toContain("id=\"mapResolve\"");
    expect(html).toContain("id=\"mapList\"");
    expect(html).toContain("Log source changes");
    expect(html).toContain("updateSourceSnapshot");
    expect(html).toContain("renderHeartbeatSummary");
    expect(html).toContain("buildHeartbeatConfigPayload");
    expect(html).toContain("/v1/stream/events");
    expect(html).toContain("streamEventsUrl");
    expect(html).toContain("WHATSAPP_PROVIDER=baileys");
    expect(html).toContain("SEND_CHAT_REQUEST");
    expect(html).toContain("selectedAuthPreference");
    expect(html).toContain("Persisted Transcript");
    expect(html).toContain("id=\"sessionTranscript\"");
    expect(html).toContain("class=\"transcript-frame\"");
    expect(html).toContain("transcriptSelectionPauseUntil");
    expect(html).toContain("isSessionTranscriptSelectionActive");
    expect(html).toContain("id=\"transcriptRefresh\"");
    expect(html).toContain("id=\"transcriptDate\"");
    expect(html).toContain("id=\"transcriptAllSessions\"");
    expect(html).toContain("All sessions");
    expect(html).toContain("TRANSCRIPT_SCOPE_UPDATE");
    expect(html).toContain("TRANSCRIPT_DAY_UPDATE");
    expect(html).toContain("resolveTranscriptDateBounds");
    expect(html).toContain("&until=");
    expect(html).toContain(".transcript-frame {");
    expect(html).toContain("width: min(100%, 800px);");
    expect(html).toContain("max-width: 800px;");
    expect(html).toContain("display: block;");
    expect(html).toContain("width: 100%;");
    expect(html).toContain("overflow-wrap: anywhere;");
    expect(html).toContain("word-break: break-word;");
    expect(html).toContain("user-select: text;");
    expect(html).toContain(".panel {");
    expect(html).toContain("min-width: 0;");
    expect(html).toContain("pollTranscriptSilently");
    expect(html).toContain("startTranscriptAutoPoll");
    expect(html).toContain("heartbeatFormDirty");
    expect(html).toContain("heartbeatEditableInputIds");
    expect(html).toContain("const nextText = lines.join(");
    expect(html).toContain("replace(");
    expect(html).toContain(".status[data-state=\"busy\"]");
    expect(html).toContain("id=\"logNewestFirst\"");
    expect(html).toContain("Newest first");
    expect(html).toContain("id=\"authSummary\"");
    expect(html).toContain("id=\"waLiveSummary\"");
    expect(html).toContain("runButtonAction");
    expect(html).toContain("MAX_LOG_ENTRIES = 500");
    expect(html).toContain("renderLog()");
  });
});
